[tool.poetry]
name = "cipher_tn2472"
version = "0.10"
description = "Caesar Cipher!"
authors = ["Timothy Ng"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
